AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/SlicingWithRange:
  Enabled: false # Prefer ary[n..] over ary[n..-1] - RubyMine 8 highlights this as a mistake

Metrics/MethodLength:
  Max: 15 # Default 10 is too strict

Metrics/CyclomaticComplexity:
  Max: 8 # Default 6 is too strict

Metrics/PerceivedComplexity:
  Max: 9 # Default 7 is too strict
