version: '3.8'

services:
  db:
    image: mdillon/postgis:9.4
    container_name: gps_collector_db
    environment:
      POSTGRES_DB: gps_collector
      POSTGRES_PASSWD: gps_collector
      POSTGRES_USER: gps_collector
    ports:
      - "5432:5432"

  rack:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: rack.Dockerfile
    volumes:
      - .:/home/app
    ports:
      - "9292:9292"
    depends_on:
      - db